// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJ_7gQ4JsMHOxP4DPXnUFeHKG4BIy6ZU',
    appId: '1:839718408691:web:5d57939a570c92bbd8c286',
    messagingSenderId: '839718408691',
    projectId: 'fitmotionai-5d0a6',
    authDomain: 'fitmotionai-5d0a6.firebaseapp.com',
    storageBucket: 'fitmotionai-5d0a6.firebasestorage.app',
    measurementId: 'G-7GWLBZCS4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbnxVfNb3wlzknHoQryhgL5Ey_9Jq_ic',
    appId: '1:839718408691:android:f9ffefa5c8935f09d8c286',
    messagingSenderId: '839718408691',
    projectId: 'fitmotionai-5d0a6',
    storageBucket: 'fitmotionai-5d0a6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCecwdKDn32xArMApmW-9kEZEGUaC1ewrg',
    appId: '1:839718408691:ios:8b7571d4bb88c374d8c286',
    messagingSenderId: '839718408691',
    projectId: 'fitmotionai-5d0a6',
    storageBucket: 'fitmotionai-5d0a6.firebasestorage.app',
    iosBundleId: 'com.example.fitmotionAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGJ_7gQ4JsMHOxP4DPXnUFeHKG4BIy6ZU',
    appId: '1:839718408691:web:7b2d1f0860d3ced2d8c286',
    messagingSenderId: '839718408691',
    projectId: 'fitmotionai-5d0a6',
    authDomain: 'fitmotionai-5d0a6.firebaseapp.com',
    storageBucket: 'fitmotionai-5d0a6.firebasestorage.app',
    measurementId: 'G-22NG038333',
  );
}
